name: unit test

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  maven-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven

      - name: Unit Test with Maven
        run: mvn --batch-mode package

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/TEST-*.xml
